MiProyecto/MiProyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('cliente/', include('cliente.urls','cliente'))
]

MiProyecto/cliente/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "cliente"
urlpatterns = [
    path('',views.index,name="index"),
]

MiProyecto/cliente/models.py
from django.db import models
 
class Pais(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.nombre
    
class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    nacimiento = models.DateField(null=True)
    pais_origen_id = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return f"{self.nombre} {self.apellido}"

MiProyecto/MiProyecto/views.py
from django.shortcuts import render

def index(request):
    return render(request,"index.html")

MiProyecto/cliente/views.py
from django.shortcuts import render
from .models import Cliente
def index(request):
    clientes = Cliente.objects.all()
    datos = {"clientes": clientes}
    return render(request,"cliente/index_cliente.html",datos)

MiProyecto/cliente/templates/cliente/index_cliente.html
{% extends 'base.html' %}
{% block CONTENIDO %}
<h1>CLIENTES</h1>
    {% for cliente in clientes %}
        <h2> {{cliente.nombre}} </h2>
        <p> {{cliente.apellido}} </p>
        <p> {{cliente.nacimiento}} </p>
        <p> {{cliente.pais_origen_id}} </p>
    {% endfor %} 
    <a href="{% url 'index' %}">Ir a menu principal</a>    
{% endblock CONTENIDO %}

MiProyecto/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block CONTENIDO %}    
    {% endblock CONTENIDO %}
</body>
</html>

MiProyecto/templates/index.html
{% extends 'base.html' %}
{% block CONTENIDO %}
<h1>Bienvenido a mi proyecto</h1>
<a href="{%url 'cliente:index' %}">Ir a Clientes</a>    
{% endblock CONTENIDO %}